spring:
  datasource:
    username: "root"
    password: "001029"
    url: "jdbc:mysql://localhost:3306/shop_one?useUnicode=true&useSSL=false&characterEncoding=utf8"
    driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:com/shopone/mapper/xml/*.xml

mybatis-plus:
  mapper-locations: classpath:com/shopone/mapper/xml/*.xml